const connectionState = {
  CONNECTION_INITIAL: "CONNECTION_INITIAL",
  CONNECTION_CONNECTING: "CONNECTION_CONNECTING",
  CONNECTION_CONNECTED: "CONNECTION_CONNECTED",
  CONNECTION_HAD_ERROR: "CONNECTION_ERROR",
};

export { connectionState };
